---
# OSP INV Role - in-memory inventory
 - name: OSP INV - Get facts
   os_server_facts:
    cloud: "{{ cloud_conn_name }}"
    region_name: RegionOne
   register: result
   tags:
    - osp_inv_get_facts

 - name: OSP INV - Add hosts
   add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.group }}"
    # ansible_ssh_private_key_file: ~/.ssh/openstack.pem
    # ansible_ssh_user: cloud-user
   with_items: "{{result.ansible_facts.openstack_servers}}"

 - name: OSP INV - Add hosts
   add_host:
     name: "{{ item.public_v4 }}"
     group: "{{ item.metadata.deployment_name }}"
     #      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
     #  ansible_ssh_user: cloud-user
   with_items: "{{result.ansible_facts.openstack_servers}}"
...
