---
# OSP SECGROUP Role
- name: OSP SECGROUP - Ensure test secgroup is created
  os_security_group:
    cloud: "{{ cloud_conn_name }}"
    state: present
    name: SG_test_app
    description: App servers port profile
  tags:
    - osp_secgroup_create_secgroup_app

- name: OSP SECGROUP - Ensure secgroup SG_test_app rules present
  os_security_group_rule:
    cloud: "{{ cloud_conn_name }}"
    security_group: SG_test_app
    protocol: "{{ item.proto }}"
    port_range_min: "{{ item.port }}"
    port_range_max: "{{ item.port }}"
    remote_ip_prefix: "{{ item.ip_prefix }}"
  with_items:
    - { proto: 'tcp', port: '8080', ip_prefix: '0.0.0.0/0' }
    - { proto: 'tcp', port: '5432', ip_prefix: '0.0.0.0/0' }
    - { proto: 'tcp', port: '22', ip_prefix: '0.0.0.0/0' }
    - { proto: 'tcp', port: '80', ip_prefix: '0.0.0.0/0' }
    - { proto: 'tcp', port: '443', ip_prefix: '0.0.0.0/0' }
    - { proto: 'icmp', port: '-1', ip_prefix: '0.0.0.0/0' }
  tags:
    - osp_secgroup_create_secgroup_rules
...
