---
# OSP KEYPAIR Role
- name: OSP KEYPAIR - Ensure key is loaded
  os_keypair:
    cloud: "{{ cloud_conn_name }}"
    state: present
    name: testkey1
    public_key_file: /tmp/id_rsa.pub
  tags:
    - osp_keypair_create_key
...
